"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const bodyParser = require("body-parser");
const users = require("./users");
const classes = require("./classes");
const rosters = require("./rosters");
const assignments = require("./assignments");
//import * as students from "./students";
exports.router = express_1.Router();
exports.router.param("userid", users.lookupUsers);
exports.router.param("classid", classes.lookupClass);
exports.router.use(bodyParser.json());
//router.use("/",authentication.authenticate);
//router.use("/users/",authentication.checkBoth);
exports.router.get("/users/", users.getUsers);
exports.router.get("/users/:userid", users.getUser);
//router.post("/users/",authentication.checkAdmin);
//router.put("/users/:userid",authentication.checkAdmin);
//router.delete("/users/:userid",authentication.checkAdmin);
exports.router.post("/users/", users.postUser);
exports.router.put("/users/:userid", users.putUser);
exports.router.delete("/users/:userid", users.deleteUser);
exports.router.get("/classes/", classes.getClasses);
exports.router.get("/classes/:classid", classes.getClass);
//router.post("/classes/",authentication.checkBoth);
//router.post("/classes/:classid",authentication.checkBoth);
//router.delete("/classes/:classid",authentication.checkBoth);
exports.router.post("/classes/", classes.createClass);
exports.router.post("/classes/:classid", classes.updateClass);
exports.router.delete("/classes/:classid", classes.deleteClass);
//router.use("/rosters/",authentication.checkBoth);
exports.router.get("/rosters/:classid/", rosters.getAllStudents);
exports.router.put("/rosters/:classid/:userid", rosters.addStudent);
exports.router.delete("/rosters/:classid/:userid", rosters.deleteStudent);
exports.router.get("/assignments/:classid/", assignments.getAllAssignments);
exports.router.get("/assignments/:classid/:assignnum");
//router.post("/assignments/:classid/",authentication.checkBoth);
//router.put("/assignments/:classid/:assignnum",authentication.checkBoth);
//router.delete("/assignments/:classid/:assignnum",authentication.checkBoth);
exports.router.post("/assignments/:classid/", assignments.createAssignment);
exports.router.put("/assignments/:classid/:assignnum", assignments.updateAssignment);
exports.router.delete("/assignments/:classid/:assignnum", assignments.deleteAssignment);
//# sourceMappingURL=routes.js.map